[project]
name = "nonebot-plugin-deer-pipe"
version = "0.2.2"
description = "A deer-pipe attendance nonebot2 plugin"
authors = [
    {name = "SNRainiar", email = "rainiar@foxmail.com"},
]
dependencies = [
    "Pillow>=10.4.0",
    "nonebot-plugin-alconna>=0.51.1",
    "nonebot-plugin-localstore>=0.7.1",
    "nonebot-plugin-userinfo>=0.2.5",
    "sqlmodel>=0.0.21",
    "aiosqlite>=0.20.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "AGPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/SamuNatsu/nonebot-plugin-deer-pipe"
Issues = "https://github.com/SamuNatsu/nonebot-plugin-deer-pipe/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "nonebot2[fastapi]>=2.3.2",
    "nonebot-adapter-console>=0.6.0",
]
